Style/WhileTrue:
  Description: Disallows while statements with a true literal as condition
  Enabled: true
  Severity: Warning

Lint/UselessAssign:
  Description: Disallows useless variable assignments
  Enabled: true
  Severity: Warning

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 30
  Enabled: true
  Severity: Warning

Style/RedundantReturn:
  Description: Reports redundant return expressions
  Enabled: false
  Severity: Warning

Excluded:
  - share/crystal-ic
  - src/highlighter.cr
  - src/pry.cr
  - tests/*